# SwiftLint Migration Configuration for Palace Project
# This is a more lenient configuration for gradual adoption

# Paths to include for linting
included:
  - Palace
  - PalaceTests
  - PalaceUIKit
  - ios-audiobooktoolkit/PalaceAudiobookToolkit
  - ios-audiobooktoolkit/PalaceAudiobookToolkitTests
  - ios-audiobook-overdrive/OverdriveProcessor

# Paths to exclude from linting
excluded:
  - Carthage
  - readium-sdk
  - readium-shared-js
  - adept-ios
  - adobe-content-filter
  - adobe-rmsdk
  - ios-tenprintcover
  - mobile-bookmark-spec
  - build
  - DerivedData
  - fastlane
  - scripts
  - "*.generated.swift"

# Start with only the most critical rules
disabled_rules:
  - todo
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - function_parameter_count
  - opening_brace  # Common formatting issue - fix with SwiftFormat
  - trailing_closure  # Style preference - can be ignored initially
  - unused_optional_binding  # Not critical for functionality

# Focus on critical opt-in rules only
opt_in_rules:
  - empty_string
  - force_unwrapping  # Critical for crash prevention
  - implicitly_unwrapped_optional  # Critical for crash prevention
  - legacy_random
  - redundant_nil_coalescing
  - unused_import

# More lenient configurations
line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 1000

file_length:
  warning: 1000
  error: 2000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 25
  error: 50

# Set a much higher warning threshold for migration
warning_threshold: 500

# Custom reporter
reporter: "xcode"
