# SwiftLint Configuration for Palace Project
# https://realm.github.io/SwiftLint/

# Paths to include for linting
included:
  - Palace
  - PalaceTests
  - PalaceUIKit
  - ios-audiobooktoolkit/PalaceAudiobookToolkit
  - ios-audiobooktoolkit/PalaceAudiobookToolkitTests
  - ios-audiobook-overdrive/OverdriveProcessor

# Paths to exclude from linting
excluded:
  - Carthage
  - readium-sdk
  - readium-shared-js
  - adept-ios
  - adobe-content-filter
  - adobe-rmsdk
  - ios-tenprintcover
  - mobile-bookmark-spec
  - build
  - DerivedData
  - fastlane
  - scripts
  - "*.generated.swift"

# Configure which rules to use
disabled_rules:
  - todo # Allow TODO comments for now

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - extension_access_modifier
  - fallthrough
  - file_header
  - first_where
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Configure specific rules
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - x
    - y

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3

# Analyzer rules (rules that require full project context)
analyzer_rules:
  - unused_import
  - unused_declaration

# Custom reporter (optional)  
reporter: "xcode"

# Configure warnings and errors
warning_threshold: 100
