#!/usr/bin/env bash
#
# test_jira_release_sync_guards.sh — decision table for the fixVersion guards in
# .github/workflows/jira-release-sync.yml.
#
# The workflow tags every PP key found in the GitHub release body. That body is
# generated by ReleaseNotes.py, which falls back to a PR's branch name, body and
# commits when its title carries no key — so it cannot distinguish the ticket a
# PR DELIVERED from one it merely MENTIONS. Two over-inclusion classes result,
# both measured in the 3.3.0 (502) run of 150 keys:
#
#   already-shipped  23 keys carried an earlier "iOS *" fixVersion.
#   not-started      10 keys had no fixVersion and sat in To Do — an Epic listed
#                    beside its delivered children (PP-4086), a QA verification
#                    task (PP-4092), and eight follow-up tickets named in commit
#                    bodies as deferred work. House style asks bodies to record
#                    what was NOT done, so those mentions are correct and
#                    recurring.
#
# The guards run inside a workflow `run:` block, so this replays their decision
# logic against the real Jira payload shapes rather than invoking the workflow.
# Keep it in step with the workflow if either guard changes.
#
# Both directions matter. A guard that skips everything would pass a test that
# only feeds it violations, and would silently drop the release's real tickets.
#
set -uo pipefail

FAILED=0
expect() { # $1=label $2=expected $3=actual
  if [ "$2" = "$3" ]; then
    printf '  ok    %-44s %s\n' "$1" "$3"
  else
    printf '  FAIL  %-44s got %s, want %s\n' "$1" "$3" "$2"; FAILED=1
  fi
}

decide() { # $1=json  -> prints SKIP:<reason> or TAG
  local ISSUE_JSON="$1" RELEASE_NAME="iOS 3.3.0"
  EXISTING=$(printf '%s' "$ISSUE_JSON" | jq -r '.fields.fixVersions[]?.name' 2>/dev/null) || EXISTING=""
  PRIOR_IOS=$(printf '%s\n' "$EXISTING" | grep -E '^iOS ' | grep -vxF "$RELEASE_NAME" || true)
  [ -n "$PRIOR_IOS" ] && { echo "SKIP:already-shipped"; return; }
  STATUS_CAT=$(printf '%s' "$ISSUE_JSON" | jq -r '.fields.status.statusCategory.key // empty' 2>/dev/null) || STATUS_CAT=""
  [ "$STATUS_CAT" = "new" ] && { echo "SKIP:not-started"; return; }
  [ -z "$STATUS_CAT" ] && { echo "TAG:status-unreadable"; return; }
  echo "TAG"
}
j() { printf '{"fields":{"fixVersions":%s,"status":{"name":"%s","statusCategory":{"key":"%s"}}}}' "$1" "$2" "$3"; }

expect "epic, To Do, no prior"            "SKIP:not-started"    "$(decide "$(j '[]' 'To Do' 'new')")"
expect "QA task, To Do, no prior"          "SKIP:not-started"    "$(decide "$(j '[]' 'To Do' 'new')")"
expect "deferred follow-up, To Do"         "SKIP:not-started"    "$(decide "$(j '[]' 'To Do' 'new')")"
expect "Done, shipped in an earlier iOS"   "SKIP:already-shipped" "$(decide "$(j '[{"name":"iOS 3.0.0"}]' 'Done' 'done')")"
expect "Code Review — real work, keep it"  "TAG"                 "$(decide "$(j '[]' 'Code Review' 'indeterminate')")"
expect "Done, first release — keep it"     "TAG"                 "$(decide "$(j '[]' 'Done' 'done')")"
expect "re-run, already this release"      "TAG"                 "$(decide "$(j '[{"name":"iOS 3.3.0"}]' 'Done' 'done')")"
expect "unreadable status must not skip"   "TAG:status-unreadable" "$(decide '')"

exit "$FAILED"
