default_platform(:ios)

platform :ios do
  lane :test do
    run_tests(
      project: "Palace.xcodeproj",
      devices: ["iPhone 12 Pro"],
      scheme: "Palace",
      destination: "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.0,arch=x86_64",
      xcargs: "ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO"
    )
  end
  lane :nodrm do
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace-noDRM",
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true,
      silent: true
    )
  end
  lane :beta do |options|
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace",
      include_symbols: true,
      include_bitcode: false,
      silent: true,
      output_name: options[:output_name],
      output_directory: options[:export_path],
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "org.thepalaceproject.palace" => "Ad Hoc 2"
        }
      }
    )
  end
  lane :appstore do |options|
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace",
      include_symbols: true,
      include_bitcode: false,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "org.thepalaceproject.palace" => "App Store 2"
        }
      }
    )
    pilot(
      api_key_path: "fastlane/fastlane.json",
      skip_submission: true,
      changelog: options[:changelog]
    )
  end
end
