default_platform(:ios)

platform :ios do
  lane :test do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "90"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "4"
    
    run_tests(
      project: "Palace.xcodeproj",
      devices: ["iPhone SE (3rd generation)"],
      scheme: "Palace",
      destination: "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=latest,arch=x86_64",
      xcargs: "ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO"
    )
  end

  lane :nodrm do
    
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace-noDRM",
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true,
      silent: true
    )
  end

  lane :beta do |options|
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "90"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "4"

    xcode_select "/Applications/Xcode_16.1.app"

    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace",
      include_symbols: true,
      include_bitcode: false,
      silent: true,
      output_name: options[:output_name],
      output_directory: options[:export_path],
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "org.thepalaceproject.palace" => "Ad Hoc 2"
        }
      }
    )
  end

  lane :appstore do |options|
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "90"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "4"

    xcode_select "/Applications/Xcode_16.1.app"

    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace",
      include_symbols: true,
      include_bitcode: false,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "org.thepalaceproject.palace" => "App Store 2"
        }
      },
      xcargs: "CODE_SIGN_IDENTITY='iPhone Distribution' PROVISIONING_PROFILE_SPECIFIER='App Store 2' -verbose"
    )

    pilot(
      api_key_path: "fastlane/fastlane.json",
      skip_submission: true,
      changelog: options[:changelog]
    )
  end
end