default_platform(:ios)

platform :ios do
  lane :test do
    run_tests(
      project: "Palace.xcodeproj",
      devices: ["iPhone 12 Pro"],
      scheme: "Palace"
    )
  end
  lane :beta do |options|
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace",
      include_symbols: true,
      include_bitcode: false,
      silent: true,
      output_name: options[:output_name],
      output_directory: options[:export_path],
      export_options: {
        method: "development",
        provisioningProfiles: { 
          "org.thepalaceproject.palace" => "Palace App"
        }
      }
    )
  end
  lane :testflight do
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Palace",
      include_symbols: true,
      include_bitcode: false,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "org.thepalaceproject.palace" => "App store"
        }
      }
    )
    pilot(
      api_key: ENV["CI_APPLE_FASTLANE_JSON"],
      skip_submission: true
    )
  end
end
