#!/bin/bash
# SpecterQA E2E Test Report Generator
# Generates a markdown report of test results for PR evidence.
# Usage: scripts/specterqa-report.sh [results_file]
#
# When run without arguments, creates a template report.
# When run with a results file (JSON), generates a full report.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
JOURNEYS_DIR="$PROJECT_DIR/.specterqa/journeys"
REPORT_DIR="$PROJECT_DIR/.specterqa/reports"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_FILE="$REPORT_DIR/e2e-report-$TIMESTAMP.md"

mkdir -p "$REPORT_DIR"

# Count journeys and steps
JOURNEY_COUNT=$(ls "$JOURNEYS_DIR"/*.yaml 2>/dev/null | wc -l | tr -d ' ')
STEP_COUNT=$(grep -h "^    - id:" "$JOURNEYS_DIR"/*.yaml 2>/dev/null | wc -l | tr -d ' ')

# Get git info
BRANCH=$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
COMMIT=$(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_VERSION=$(grep -A1 "CFBundleShortVersionString" "$PROJECT_DIR/Palace/Info.plist" 2>/dev/null | tail -1 | sed 's/.*<string>//;s/<.*//' || echo "unknown")

# Get simulator info
SIM_INFO=$(xcrun simctl list devices booted 2>/dev/null | grep -i iphone | head -1 | sed 's/^[[:space:]]*//' || echo "No booted simulator")

# Parse journey metadata
generate_journey_table() {
    echo "| # | Journey | Steps | Tier | Tags |"
    echo "|---|---------|-------|------|------|"
    local n=0
    for f in "$JOURNEYS_DIR"/*.yaml; do
        n=$((n + 1))
        local id=$(grep "^  id:" "$f" | head -1 | awk '{print $2}')
        local steps=$(grep "^    - id:" "$f" | wc -l | tr -d ' ')
        local tags=$(grep "tags:" "$f" | head -1 | sed 's/.*\[//;s/\]//')
        local tier="tier2"
        echo "$tags" | grep -q "smoke" && tier="smoke"
        echo "$tags" | grep -q "tier1" && tier="tier1"
        printf "| %d | %s | %s | %s | %s |\n" "$n" "$id" "$steps" "$tier" "$tags"
    done
}

# Generate the report
cat > "$REPORT_FILE" << REPORT
# SpecterQA E2E Test Report

**Generated:** $(date "+%Y-%m-%d %H:%M:%S %Z")
**Branch:** \`$BRANCH\`
**Commit:** \`$COMMIT\`
**App Version:** $BUILD_VERSION
**Simulator:** $SIM_INFO
**Library:** A1QA Test Library (gorgon.staging.palaceproject.io)

## Summary

| Metric | Value |
|--------|-------|
| Total Journeys | $JOURNEY_COUNT |
| Total Steps | $STEP_COUNT |
| Passed | — |
| Failed | — |
| Skipped | — |

> Fill in pass/fail counts after running tests.
> Attach screenshots or logs as evidence where possible.

## Test Environment

- **Xcode:** $(xcodebuild -version 2>/dev/null | head -1 || echo "unknown")
- **iOS Runtime:** $(xcrun simctl list runtimes 2>/dev/null | grep "iOS" | tail -1 | awk '{print $2}' || echo "unknown")
- **SpecterQA:** $(pip3 show specterqa-ios 2>/dev/null | grep Version | awk '{print $2}' || echo "unknown")
- **Test Mode:** Direct (no clone)

## Journey Results

$(generate_journey_table)

## How to Reproduce

\`\`\`bash
# 1. Kill stale runners
kill -9 \$(pgrep -f "xcodebuild test-without-building") 2>/dev/null

# 2. Boot simulator and set up
xcrun simctl boot <UDID>
xcrun simctl spawn <UDID> defaults write org.thepalaceproject.palace showDeveloperSettings -bool true
xcrun simctl spawn <UDID> defaults write org.thepalaceproject.palace NYPLUseBetaLibrariesKey -bool true

# 3. Build and install
xcodebuild -project Palace.xcodeproj -scheme Palace -destination 'platform=iOS Simulator,id=<UDID>' build
xcrun simctl install <UDID> <path_to_Palace.app>
xcrun simctl launch <UDID> org.thepalaceproject.palace

# 4. Sign in to A1QA Test Library (credentials in ~/.specterqa/credentials/a1qa-test.env)

# 5. Start SpecterQA session and run journeys via Claude Code

# 6. IMPORTANT: Sign out before terminating to protect DRM activations
\`\`\`

## Notes

- Audiobook playback requires full download (~7 hours of audio) — verified borrow/return only
- PDF reading verified via catalog format display — no dedicated PDF content on A1QA
- Sample content verified via preview links — requires OverDrive content for full playback
- Dark mode must be set via \`xcrun simctl ui\` BEFORE starting SpecterQA session
- Sign-in form text fields require the accessibility fix (\`.accessibilityElement(children: .contain)\`)

---
*Report generated by \`scripts/specterqa-report.sh\`*
REPORT

echo "Report generated: $REPORT_FILE"
echo ""
echo "To include in PR, copy the Summary and Journey Results sections."
