name: Palace Manual Release
on: workflow_dispatch
jobs:
  create-release:
    runs-on: macOS-latest
    steps:
      - name: Force Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode_16.app
      - name: Checkout main repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
      - name: Checkout Certificates
        uses: actions/checkout@v3
        with:
          repository: ThePalaceProject/mobile-certificates
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          path: ./mobile-certificates
      - name: Create release notes
        run: ./scripts/create-release-notes.sh
        env:
          BUILD_CONTEXT: ci
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
      - name: Verify path and version
        run: |
          echo "Release notes path: " $RELEASE_NOTES_PATH
          cat $RELEASE_NOTES_PATH
          echo "Changelog path:     " $CHANGELOG_PATH
          cat $CHANGELOG_PATH
          echo "Version:            " $VERSION_NUM
        env:
          RELEASE_NOTES_PATH: ${{ env.RELEASE_NOTES_PATH }}
          CHANGELOG_PATH: ${{ env.CHANGELOG_PATH }}
          VERSION_NUM: ${{ env.VERSION_NUM }}          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES_PATH: ${{ env.RELEASE_NOTES_PATH }}
          VERSION_NUM: ${{ env.VERSION_NUM }}
        with:
          tag_name: ${{ env.VERSION_NUM }}
          release_name: ${{ env.VERSION_NUM }}
          body_path: ${{ env.RELEASE_NOTES_PATH }}
          draft: false
